"""
Centralized constants for the application to avoid magic numbers.
"""

# --- Asset Handling ---
MAX_FILENAME_LENGTH = 100
FILENAME_RESERVED_CHARS = r"[^a-zA-Z0-9_.-]"
ASSET_DOWNLOAD_CONCURRENCY = 20
ASSET_DOWNLOAD_TIMEOUT = 30.0

# --- LLM Interactions ---
LLM_API_TIMEOUT = 240.0
LLM_HTML_API_TIMEOUT = 300.0
LLM_DESCRIPTION_MAX_TOKENS = 4096
LLM_HTML_MAX_TOKENS = 4096
GEMINI_HTML_MAX_OUTPUT_TOKENS = 32000

# --- Screenshotting ---
SCREENSHOT_GOTO_TIMEOUT = 45000  # ms
SCREENSHOT_NETWORK_IDLE_WAIT = 2500  # ms
SCREENSHOT_CAPTURE_TIMEOUT = 20000  # ms
