global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
  - job_name: 'api'
    static_configs:
      - targets: ['api:8000'] # Assuming FastAPI exposes a /metrics endpoint
